# Generated by Django 5.1.5 on 2025-01-17 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField()),
                ('data_nascimento_tomador', models.DateField()),
                ('valor_desembolsado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_documento', models.CharField(max_length=14)),
                ('endereco_tomador', models.JSONField()),
                ('telefone_tomador', models.CharField(max_length=15)),
                ('taxa_contrato', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='gerenciamento_credito_app.contrato')),
            ],
        ),
    ]
